apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-onmp
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0061-tenant/tkwch-fix-0075-0061-app/devfile-sample-onmp@sha256:ecc6837cea411de8a6cd04b385e2eee14f981fff51cd8842e5203abf7b3701c6
        name: my-nodejs
        resources: {}
status: {}
