apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-onmp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-onmp
    app.kubernetes.io/part-of: tkwch-fix-0075-0061-app
  name: devfile-sample-onmp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-onmp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-onmp
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0061-tenant/tkwch-fix-0075-0061-app/devfile-sample-onmp@sha256:ecc6837cea411de8a6cd04b385e2eee14f981fff51cd8842e5203abf7b3701c6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
